version: '3.8'

services:

  backend:
    build:
      args:
        user: admin
        uid: 1000
      context: .
      dockerfile: ./_docker/backend/Dockerfile
    restart: unless-stopped
#    extra_hosts:
#      - "search.local:127.0.0.1"
    env_file:
      - phoneroom_back/.env
    tty: true
    expose:
      - 8000
    ports:
      - "8000:8000"
    networks:
      net:
        ipv4_address: 192.168.0.153
    volumes:
      - ./phoneroom_back:/var/www/back
      - ./_docker/backend/php.ini:/usr/local/etc/php/php.ini

  nginx-front:
    image: nginx:latest
    restart: unless-stopped
    tty: true
    networks:
      net:
        ipv4_address: 192.168.0.150
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./phoneroom_client:/var/www/front
      - ./_docker/nginx/nginx-front.conf:/etc/nginx/conf.d/nginx-front.conf
    links:
      - frontend

  nginx-back:
    image: nginx:latest
    restart: unless-stopped
    tty: true
    networks:
      net:
        ipv4_address: 192.168.0.151
#    ports:
#      - "8000:80"
#      - "8000:443"
    volumes:
      - ./phoneroom_back:/var/www/back
      - ./_docker/nginx/nginx-back.conf:/etc/nginx/conf.d/nginx-back.conf
#    depends_on:
#      - backend

  frontend:
    build:
      context: .
      dockerfile: ./_docker/nodejs/Dockerfile
    tty: true
    extra_hosts:
      - "search.local:127.0.0.1"
    env_file:
      - phoneroom_client/.env
    networks:
      net:
        ipv4_address: 192.168.0.154
    expose:
      - 3000
#    links:
##      - nginx-front
#      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./phoneroom_client:/var/www/front

#  meilisearch:
#    container_name: meilisearch
#    image: getmeili/meilisearch:v1.0
##    environment:
##      - http_proxy
##      - https_proxy
##      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
##      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
##      - MEILI_ENV=${MEILI_ENV:-development}
##      - MEILI_LOG_LEVEL
##      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
#    ports:
#      - ${MEILI_PORT:-7700}:7700
#    networks:
#      - bridge
##    volumes:
##      - ./data.ms:/data.ms
#    restart: unless-stopped

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24